# Generated by Django 4.2.2 on 2023-06-22 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('LogonId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('SaltedHash', models.CharField(max_length=256)),
                ('Salt', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('PhotoURL', models.CharField(max_length=1000)),
                ('Credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.login')),
            ],
        ),
    ]
