import * as React from 'react';

import Container from '@mui/material/Container';
import {useCallback, useContext} from "react";
import {ScreenContext} from "../App";
import FormControl from "@mui/material/FormControl";
import {FormControlLabel, FormGroup, FormHelperText, FormLabel, Switch} from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";
import {createTheme, ThemeProvider} from "@mui/material/styles";
import Box from "@mui/material/Box";
import {darkTheme, lightTheme} from "../utils/Themes";

const defaultTheme = createTheme();

const Settings = () => {
  const { screenState, setScreenState } = useContext(ScreenContext);

  const handleChange = useCallback(() => {
    setScreenState({
      ...screenState,
      generativeMode: !screenState.generativeMode
    });
  }, [screenState]);

  return (
    <ThemeProvider theme={screenState.darkMode ? darkTheme : lightTheme}>
      <CssBaseline />
      <main>
        <Box
          sx={{
            bgcolor: 'background.paper',
            pt: 2,
            pb: 2,
          }}
        >
          <Container maxWidth="sm" sx={{
            margin: 0
          }}>
            <FormControl component="fieldset" variant="standard">
              <FormLabel component="legend">Application Configuration</FormLabel>
              <FormGroup sx={{ margin: 2 }}>
                <FormControlLabel
                  control={
                    <Switch checked={screenState.generativeMode} onChange={handleChange} name="generativeMode" />
                  }
                  label="Allow Generative Mode"
                />
              </FormGroup>
              <FormHelperText>Generative Mode allows students to see answers generated by the GP2 Model</FormHelperText>
            </FormControl>
          </Container>
        </Box>
      </main>
    </ThemeProvider>
  );
}

export default Settings;