# Generated by Django 4.2.2 on 2023-06-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('ChatId', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('QueryId', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=500)),
                ('Answer', models.CharField(max_length=1000)),
            ],
        ),
    ]
